# Phase 1: Data Cleaning and Understanding

## Global Disaster Response Analysis (2018–2024)

### Objective
- The objective of Phase-1 is to understand the dataset structure, check data quality,
handle missing or inconsistent values, and prepare the data for further analysis.

In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

# 📜 Project: Data Understanding Report

## Data Exploration & Initial Assessment

##  🧠Project Context

- This project analyzes data related to natural disasters that occurred worldwide between 2018 and 2024.

- The dataset captures key information about each disaster event, including its impact, response, and recovery.

- Using this data, the project aims to answer important questions such as:

           - How much damage was caused by each disaster?

           - How many people were affected?

           - How quickly did emergency response teams react?

           - Was the aid effectively delivered to the affected regions?


  
- Overall, the goal of this project is to use data-driven insights to evaluate disaster response effectiveness and identify areas for improvement.

## 🌎 Step 1: Data Understanding

### → Before any cleaning, analysis, or modeling We have anyalze that :

#### ⁕ What columns are present?

#### The dataset contains the following columns:

- 1.date
- 2.country
- 3.disaster_type
- 4.severity_index
- 5.casualties
- 6.economic_loss_usd
- 7.response_time_hours
- 8.aid_amount_usd
- 9.response_efficiency_score
- 10.recovery_days
- 11.latitude
- 12.longitude

## → What kind of data does each column contain?

- 1.date:
Contains the date on which the disaster occurred.

- 2.country:
Represents the country where the disaster took place.

- 3.disaster_type:
Indicates the type of disaster (such as flood, earthquake, cyclone, etc.).

- 4.severity_index:
A numerical measure representing the intensity or severity of the disaster.

- 5.casualties:
The total number of people injured or killed due to the disaster.

- 6.economic_loss_usd:
The estimated financial loss caused by the disaster, measured in US dollars.

- 7.response_time_hours:
The number of hours taken for emergency response teams to reach the affected area.

- 8.aid_amount_usd:
The amount of financial aid provided for disaster relief, in US dollars.

- 9.response_efficiency_score:
A numerical score that represents how effective the disaster response was.

- 10.recovery_days:
The number of days required for the affected region to return to normal conditions.

- 11.latitude:
The geographical latitude of the disaster location.

- 12.longitude:
The geographical longitude of the disaster location.

### → Are there any missing or unusual values?

- The dataset does not contain any missing (null) values, indicating good data quality.

- All columns follow appropriate data types (dates, numerical values, and categorical values).

- No unusual or inconsistent values were observed, such as negative losses or invalid response times.

- The dataset is suitable for exploratory data analysis and visualization without additional data cleaning

## Reading Dataset

In [2]:
df=pd.read_csv(r"C:\Users\ch.sindhu sri\OneDrive\Pictures\Documents\OneDrive\Desktop\Inno Pandas\global_disaster_response_2018_2024 .csv")
df

,date,country,disaster_type,severity_index,casualties,economic_loss_usd,response_time_hours,aid_amount_usd,response_efficiency_score,recovery_days,latitude,longitude
0,2021-01-31,Brazil,Earthquake,5.99,111,7934365.71,15.62,271603.79,83.21,67,-30.613,-122.557
1,2018-12-23,Brazil,Extreme Heat,6.53,100,8307648.99,5.03,265873.81,96.18,55,10.859,-159.194
2,2020-08-10,India,Hurricane,1.55,22,765136.99,32.54,49356.49,60.40,22,0.643,-160.978
3,2022-09-15,Indonesia,Extreme Heat,4.55,94,1308251.31,7.83,237512.88,86.41,47,-33.547,30.350
4,2022-09-28,United States,Wildfire,3.80,64,2655864.36,21.90,188910.69,72.81,42,-19.170,-117.137
...,...,...,...,...,...,...,...,...,...,...,...,...
49995,2019-05-14,Chile,Landslide,5.50,78,3711240.93,8.45,305020.35,94.27,55,12.976,-25.680
49996,2020-10-30,United States,Wildfire,7.76,165,12072842.65,1.00,363881.25,95.46,76,57.265,-147.346
49997,2019-04-27,Turkey,Flood,4.90,130,1805859.70,5.14,280665.61,86.67,47,15.217,-27.856
49998,2022-10-09,Greece,Storm Surge,3.35,82,3176085.56,19.22,80331.23,84.75,32,-44.002,1.923
49999,2023-01-12,South Africa,Drought,5.03,129,2933495.70,9.08,354096.99,97.16,50,13.084,-81.048

### For Viewing sample data

In [3]:
df.head()

,date,country,disaster_type,severity_index,casualties,economic_loss_usd,response_time_hours,aid_amount_usd,response_efficiency_score,recovery_days,latitude,longitude
0,2021-01-31,Brazil,Earthquake,5.99,111,7934365.71,15.62,271603.79,83.21,67,-30.613,-122.557
1,2018-12-23,Brazil,Extreme Heat,6.53,100,8307648.99,5.03,265873.81,96.18,55,10.859,-159.194
2,2020-08-10,India,Hurricane,1.55,22,765136.99,32.54,49356.49,60.40,22,0.643,-160.978
3,2022-09-15,Indonesia,Extreme Heat,4.55,94,1308251.31,7.83,237512.88,86.41,47,-33.547,30.350
4,2022-09-28,United States,Wildfire,3.80,64,2655864.36,21.90,188910.69,72.81,42,-19.170,-117.137

### Checking structure of the Dataset

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 12 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   date                       50000 non-null  object
 1   country                    50000 non-null  object
 2   disaster_type              50000 non-null  object
 3   severity_index             50000 non-null  float64
 4   casualties                 50000 non-null  int64
 5   economic_loss_usd          50000 non-null  float64
 6   response_time_hours        50000 non-null  float64
 7   aid_amount_usd             50000 non-null  float64
 8   response_efficiency_score  50000 non-null  float64
 9   recovery_days              50000 non-null  int64
 10  latitude                   50000 non-null  float64
 11  longitude                  50000 non-null  float64
dtypes: float64(7), int64(2), object(3)
memory usage: 4.6+ MB

## Checking Summary Statistics of Numerical Column

In [5]:
df.describe()

,severity_index,casualties,economic_loss_usd,response_time_hours,aid_amount_usd,response_efficiency_score,recovery_days,latitude,longitude
count,50000.000000,50000.000000,5.000000e+04,50000.000000,5.000000e+04,50000.000000,50000.000000,50000.000000,50000.000000
mean,5.015769,100.591140,5.068593e+06,12.183027,2.500003e+05,87.574025,49.682560,0.231205,0.089889
std,1.942843,65.052064,3.268541e+06,9.259081,1.432275e+05,10.188961,20.098944,34.759662,98.380208
min,1.000000,0.000000,5.273900e+02,1.000000,1.660000e+01,29.750000,2.000000,-59.994000,-169.998000
25%,3.660000,51.000000,2.585513e+06,6.270000,1.429663e+05,83.060000,36.000000,-29.848250,-85.551750
50%,4.990000,91.000000,4.548351e+06,10.510000,2.305365e+05,89.180000,49.000000,0.267500,0.390500
75%,6.340000,138.000000,6.950615e+06,15.450000,3.352259e+05,94.700000,63.000000,30.488250,85.665000
max,10.000000,524.000000,2.445624e+07,63.100000,1.126465e+06,100.000000,112.000000,59.997000,169.999000

## Checking Summary Statistics of Categorical Column

In [6]:
df.describe(include='O')

              date country disaster_type
count        50000   50000         50000
unique        2557      20            10
top     2023-08-29  Brazil     Landslide
freq            36    2591          5130

## Checking Missing Values

In [7]:
df.isna().sum()

date                         0
country                      0
disaster_type                0
severity_index               0
casualties                   0
economic_loss_usd            0
response_time_hours          0
aid_amount_usd               0
response_efficiency_score    0
recovery_days                0
latitude                     0
longitude                    0
dtype: int64

## Checking Duplicates

In [8]:
df.duplicated().sum()

np.int64(0)

### Understanding categories

In [9]:
df.value_counts()

date        country        disaster_type  severity_index  casualties  economic_loss_usd  response_time_hours  aid_amount_usd  response_efficiency_score  recovery_days  latitude  longitude
2018-01-01  Australia      Extreme Heat   7.54            192         4890656.60         16.93                271955.25       81.14                      78             -23.062   -107.634     1
                           Hurricane      5.98            189         11992685.37        2.13                 609789.44       100.00                     65              23.927   -166.386     1
            Bangladesh     Storm Surge    1.90            18          1015818.73         22.33                57572.60        80.00                      17              33.981   -59.912      1
                           Tornado        2.96            15          1576231.83         20.70                148866.72       76.98                      30             -41.519    166.032     1
                           Wildfire       6.52            15          1548114.15         7.82                 242303.94       95.39                      54             -50.037   -166.271     1
                                                                                                                                                                                              ..
2024-12-31  Spain          Landslide      3.00            86          1889422.97         16.33                241688.11       84.65                      28              50.952    115.004     1
            United States  Earthquake     6.04            83          2479539.25         5.71                 255257.62       97.50                      63             -15.470   -42.444      1
                           Flood          5.22            203         5102853.58         17.87                381253.72       85.03                      53              57.684   -144.917     1
                           Hurricane      4.49            103         6416229.45         13.70                55355.26        86.35                      41              44.064    143.206     1
                           Tornado        10.00           203         15536454.01        4.02                 693145.41       96.49                      104             23.212   -116.883     1
Name: count, Length: 50000, dtype: int64

### Data type of each column

In [10]:
df.dtypes

date                          object
country                       object
disaster_type                 object
severity_index               float64
casualties                     int64
economic_loss_usd            float64
response_time_hours          float64
aid_amount_usd               float64
response_efficiency_score    float64
recovery_days                  int64
latitude                     float64
longitude                    float64
dtype: object

### So,Here date column is in object datatype so we need to convert it into datetime format

In [11]:
df['date'] = pd.to_datetime(df['date'])

In [12]:
df.dtypes

date                         datetime64[ns]
country                              object
disaster_type                        object
severity_index                      float64
casualties                            int64
economic_loss_usd                   float64
response_time_hours                 float64
aid_amount_usd                      float64
response_efficiency_score           float64
recovery_days                         int64
latitude                            float64
longitude                           float64
dtype: object

### Shape of your dataset (rows and columns)?

In [13]:
df.shape

(50000, 12)

### Checking each column if any missing values in any column

In [14]:
df['date'].dtypes

dtype('<M8[ns]')

In [15]:
print(df['date'].isnull().sum())

0

In [16]:
print(df['date'].unique())

<DatetimeArray>
['2021-01-31 00:00:00', '2018-12-23 00:00:00', '2020-08-10 00:00:00',
 '2022-09-15 00:00:00', '2022-09-28 00:00:00', '2019-01-15 00:00:00',
 '2020-12-19 00:00:00', '2022-03-31 00:00:00', '2024-06-22 00:00:00',
 '2018-11-23 00:00:00',
 ...
 '2023-02-11 00:00:00', '2022-12-15 00:00:00', '2018-10-31 00:00:00',
 '2019-09-15 00:00:00', '2022-09-09 00:00:00', '2019-09-02 00:00:00',
 '2019-11-14 00:00:00', '2020-12-04 00:00:00', '2020-08-30 00:00:00',
 '2018-09-25 00:00:00']
Length: 2557, dtype: datetime64[ns]

In [17]:
df['country'].dtypes

dtype('O')

In [18]:
print(df['country'].isnull().sum())

0

In [19]:
print(df['country'].unique())

['Brazil' 'India' 'Indonesia' 'United States' 'France' 'Germany' 'Greece'
 'Spain' 'Mexico' 'South Africa' 'Philippines' 'Nigeria' 'Japan' 'Canada'
 'Italy' 'Australia' 'China' 'Bangladesh' 'Chile' 'Turkey']

In [20]:
df['disaster_type'].dtypes

dtype('O')

In [21]:
print(df['disaster_type'].isnull().sum())

0

In [22]:
print(df['disaster_type'].unique())

['Earthquake' 'Extreme Heat' 'Hurricane' 'Wildfire' 'Flood' 'Storm Surge'
 'Drought' 'Tornado' 'Landslide' 'Volcanic Eruption']

In [23]:
df['severity_index'].dtypes

dtype('float64')

In [24]:
print(df['severity_index'].isnull().sum())

0

In [25]:
print(df['severity_index'].unique())

[ 5.99  6.53  1.55  4.55  3.8   2.56  4.77  1.47  3.32  2.61  5.72  4.4
  3.38  6.94  5.01  5.81  5.12  6.5   3.02  5.95  5.45  2.36  5.59  6.57
  4.51  6.65  2.86  1.97  3.23  7.11  6.14  4.53  4.06  5.43  3.68  4.33
  9.24  6.55  8.26  5.02  5.23  6.18  5.71  3.88  6.09  5.04  3.36  6.26
  3.35  3.99  5.62  4.42  6.38  6.    9.38  5.3   7.48  7.56  9.12  6.37
  8.    4.93  3.97  3.41  3.6   3.85  6.15  5.41  4.98  4.62  3.7   4.9
  5.2   1.39  4.87  5.51  5.58  2.98  6.66  4.17  3.98  6.74  7.99  5.22
  7.69  1.62  5.15  7.25  5.4   5.21  4.31  7.54  4.52  6.23  3.95  8.51
  4.92  1.58  3.92  3.75  2.19  4.81  6.42  4.5   6.12  5.42  5.06  4.38
  7.89  7.13  8.16  3.46  9.91  7.84  6.32  8.59  4.02  7.22  4.67  5.37
  7.39  8.76  5.49  2.5   5.9   3.65  3.69  6.75  3.    6.85  7.1   4.95
  2.95  2.55  7.35  4.28  5.86  6.46  5.69  7.21  3.49  7.75  8.19  7.02
  2.22  6.71  1.61  1.86  6.1   5.1   3.61  3.33  4.74  4.82  5.07  5.75
  3.19  7.43  4.7   2.79  4.8   4.65  2.87  5.97  8.06  6.9   1.4   2.04
  4.68  2.26  8.65  7.6   5.27  2.91  3.71  7.15  4.56  5.57  5.36  6.51
  3.3   5.84 10.    7.05  4.09  3.57  8.71  8.77  4.94  5.6   3.51  1.87
  2.97  5.17  6.24  3.4   3.5   8.75  3.31  9.13  5.39  7.28  3.16  5.25
  5.98  4.73  6.48  8.68  2.89  7.32  1.    6.91  8.39  4.14  2.08  5.53
  6.79  7.82  3.78  1.24  3.66  6.59  4.18  3.82  8.2   4.79  9.46  4.66
  4.07  4.89  4.96  2.24  3.72  7.14  3.42  6.88  4.47  2.38  6.61  3.27
  3.83  5.18  4.1   2.72  6.28  6.43  5.35  1.71  4.25  6.97  5.92  5.94
  6.76  2.34  2.83  5.5   4.36  3.77  4.99  4.86  7.19  5.82  3.93  3.07
  3.15  4.83  6.62  5.54  4.54  3.17  5.48  9.73  2.32  6.72  4.01  5.68
  4.49  6.21  2.48  7.04  6.07  7.93  7.45  7.47  5.91  3.28  5.8   4.26
  7.06  2.65  2.53  7.86  9.02  8.13  6.25  7.96  7.46  8.15  2.74  6.64
  5.96  8.67  6.69  7.95  3.56  6.36  3.73  4.43  3.54  7.59  6.99  3.1
  1.36  9.82  5.52  8.78  1.26  4.21  7.4   7.44  3.79  6.68  2.69  6.22
  6.95  7.66  9.56  5.87  3.45  8.05  2.9   7.5   2.44  5.46  6.29  7.34
  3.11  7.2   7.24  8.18  1.63  7.38  2.23  9.09  5.93  2.45  6.39  2.49
  2.33  7.77  7.36  4.88  1.34  4.41  5.14  5.67  4.64  6.49  4.72  3.86
  2.13  9.62  3.76  3.34  7.51  3.05  3.48  1.8   6.31  1.41  4.91  5.32
  1.93  5.76  7.65  4.44  7.58  6.01  2.75  2.27  3.96  2.7   3.62  6.4
  4.11  2.94  7.7   1.96  7.26  4.03  9.7   5.09  5.55  2.64  3.44  3.03
  3.81  1.84  3.67  6.17  3.2   5.7   1.1   4.32  7.3   6.7   3.84  2.29
  3.9   7.79  6.58  3.87  7.62  3.53  3.64  5.26  1.77  9.31  7.55  6.19
  6.45  5.28  4.19  2.46  2.47  2.21  4.16  7.64  4.97  7.33  2.51  4.75
  4.22  5.61  2.42  4.61  6.13  6.08  2.57  7.09  6.78  5.16  4.04  6.04
  3.01  5.44  1.31  6.92  2.2   3.52  5.83  2.01  5.56  5.38  8.37  6.47
  2.3   2.78  3.58  5.33  4.29  4.27  5.03  5.77  4.24  1.44  6.41  9.99
  1.51  1.19  6.03  2.39  5.19  8.64  4.76  2.54  3.91  3.74  3.18  8.34
  3.21  1.91  7.74  5.    2.66  1.99  2.15  2.31  8.74  5.13  3.26  5.29
  4.69  4.39  9.58  5.11  2.99  2.92  7.78  4.71  9.29  4.48  5.88  7.67
  3.37  1.2   4.08  6.06  8.1   5.79  7.8   1.32  3.43  5.73  8.07  8.14
  3.39  3.22  2.82  8.82  7.71  1.75  4.46  7.41  8.35  3.25  7.63  5.05
  4.23  7.17  8.11  8.38  3.13  9.9   5.24  8.08  4.05  7.08  5.63  7.73
  9.25  9.81  6.33  6.89  6.52  4.    7.88  1.66  3.09  2.96  3.89  5.31
  5.47  7.57  3.12  3.14  4.3   3.59  4.37  1.38  1.89  2.84  3.24  6.35
  1.94  9.15  4.2   8.28  4.57  1.02  1.59  5.66  7.01  4.85  1.9   8.97
  3.06  4.35  5.89  1.76  4.58  4.13  6.02  1.06  3.04  7.76  7.83  6.77
  7.31  6.44  4.15  4.45  1.57  4.6   6.63  1.6   9.07  2.16  3.94  2.8
  6.56  8.57  1.27  1.46  8.85  2.11  8.49  5.34  9.05  8.33  1.78  6.27
  8.04  2.85  5.74  6.87  6.05  2.28  6.83  8.23  6.84  2.12  8.7   6.82
  8.02  8.03  4.78  2.02  6.6   7.27  2.37  8.79  8.62  3.63  1.23  1.3
  1.29  1.22  4.84  1.85  7.16  8.25  7.91  8.46  7.37  2.63  6.81  1.64
  2.14  1.37  7.53  9.67  7.61  8.21  2.6   2.18  2.1   5.65  2.35  6.8
  8.36  3.55  9.6   4.34  6.34  1.82  2.76  5.64  9.08  1.52  7.72  6.3
  6.93  2.09  9.14  1.69  1.79  7.68  1.73  6.2   5.08  1.42  7.94  8.6
  2.05  7.42  5.78  9.44  3.08  8.01  9.79  4.63  6.11  1.83  8.53  9.64
  6.98  2.93  8.72  8.43  7.07  2.43  2.88  4.59  8.4   3.29  7.18  2.17
  2.58  7.87  8.45  1.98  8.41  7.03  5.85  2.07  7.23  2.77  2.06  1.07
  9.28  2.    2.4   9.85  8.27  8.44  9.52  6.54  8.5   7.97  1.7   9.04
  4.12  7.85  6.67  8.52  6.16  6.86  9.63  7.52  8.61  9.33  9.49  8.42
  1.43  9.43  8.96  2.73  9.16  2.62  7.49  7.12  2.68  8.84  8.3   7.9
  9.42  2.81  8.56  2.41  8.98  6.73  1.68  7.81  7.29  8.94  1.88  1.5
  3.47  8.69  8.89  8.73  1.48  1.08  1.65  8.95  2.59  9.88  8.47  8.93
  9.3   1.15  9.03  6.96  2.25  9.4   2.52  9.5   1.04  8.81  2.67  7.98
  9.51  8.63  1.54  8.66  1.17  9.1   9.06  8.99  8.29  1.25  9.69  9.39
  7.92  9.55  9.83  1.33  7.    1.12  1.53  2.71  8.91  8.58  8.48  1.35
  1.95  8.87  9.96  1.13  9.47  1.05  1.67  8.09  9.97  8.32  1.74  8.12
  1.92  9.26  9.32  8.8   9.27  1.18  1.03  1.16  1.72  8.86  1.14  9.76
  8.22  8.17  1.45  8.92  1.21  8.31  9.66  8.88  1.09  1.56  9.21  9.
  8.54  1.11  9.45  9.72  9.57  1.81  9.75  1.49  9.22  9.35  9.89  9.01
  9.23  9.68  8.55  8.24  9.18  9.37  1.01  9.54  9.61  9.94  9.11  9.93
  9.2   9.17  9.53  9.78  9.41  1.28  9.19  2.03  9.95  9.74  8.83  8.9
  9.92  9.36  9.8   9.98  9.84  9.48  9.77  9.87  9.65  9.34  9.59  9.71
  9.86]

In [26]:
df['casualties'].dtypes

dtype('int64')

In [27]:
print(df['casualties'].isnull().sum())

0

In [28]:
print(df['casualties'].unique())

[111 100  22  94  64  56  81  34  73 202  92  50  90  88 225 228 181  43
 180  59  71 207 133  70  30  69  44 192  68 125 104  66 280  47  51 139
 140  74 106 109 135 137 124  60 195 102 206  53 176 342 194 166   3  37
  79 142  67 173  55  86 143   5  38 110 128 227  14  76 226 212 276  57
  36  77 205 161 120   6 152  10 134  75  23 130 151 188 123  97 105 131
 112 253 127 122 203 165  83  35  48  78  13  85 155 138 159 141 103  72
  89 186 177 132 170  58 229   7 185  18  46  96 220  62 126  40   4 117
 259   8 231 270 108 116 154 182 310 107  27  61  19 269 241 114 157 169
  26 249  52 115  54 196  98 148  17 168  16 209 119 113  84   0  24 121
  82  63 174  80  31 260 216 238  42 187 293 198 219  11  32  91  95 136
 118 146 324 266 252 287 237 230  49 204  25  29   1 242 272 315 274  20
 171 251 243 153  15 101 147 345  41 224 160 158 244  99 208  33 156 312
 210 232 163 214 145  12 218 267 150  45 193 308 222 164  21  39 167 201
 246   9 221 223  93 149  65  28 183 263  87 197 261 248 178 162 370 129
 215 189 233   2 279 257 211 394 200 184 217 190 289 385 247 313 213 362
 144 281 236 172 250 295 179 321 302 307 240 318 245 346 199 347 364 337
 175 235 275 306 284 255 239 282 294 288 258 389 301 191 304 393 438 285
 265 292 316 327 273 328 234 391 355 384 296 264 349 254 329 277 331 256
 262 369 283 360 297 351 291 271 339 268 290 359 319 305 372 419 278 340
 341 386 368 309 325 330 445 428 406 311 320 300 322 434 303 376 333 326
 353 286 323 373 429 352 298 314 348 477 344 317 332 334 375 367 299 420
 403 408 358 343 524 382 461 338 454 350 354 357 390 335 356 380 371 415
 366 431 361 377 413 398 416 387 397 365 374]

In [29]:
df['economic_loss_usd'].dtypes

dtype('float64')

In [30]:
print(df['economic_loss_usd'].isnull().sum())

0

In [31]:
print(df['economic_loss_usd'].unique())

[7934365.71 8307648.99  765136.99 ... 1805859.7  3176085.56 2933495.7 ]

In [32]:
df['response_time_hours'].dtypes

dtype('float64')

In [33]:
print(df['response_time_hours'].isnull().sum())

0

In [34]:
print(df['response_time_hours'].unique())

[15.62  5.03 32.54 ... 26.08 45.97 26.86]

In [35]:
df['aid_amount_usd'].dtypes

dtype('float64')

In [36]:
print(df['aid_amount_usd'].isnull().sum())

0

In [37]:
print(df['aid_amount_usd'].unique())

[271603.79 265873.81  49356.49 ... 280665.61  80331.23 354096.99]

In [38]:
df['response_efficiency_score'].dtypes

dtype('float64')

In [39]:
print(df['response_efficiency_score'].isnull().sum())

0

In [40]:
print(df['response_efficiency_score'].unique())

[83.21 96.18 60.4  ... 57.41 42.09 56.46]

In [41]:
df['recovery_days'].dtypes

dtype('int64')

In [42]:
print(df['recovery_days'].isnull().sum())

0

In [43]:
print(df['recovery_days'].unique())

[ 67  55  22  47  42  26  49  19  27  57  41  34  70  56  75  24  53  48
  50  46  62  21  37  90  36  30  94  59  88  51  66  52  35  61  38  63
  60  23  77  20  86  81  44  33  58   5  45  28  68  71  80  82  43  54
  72  78  39  87  17  79  76 105  83  91  64  40  73  69  65  25  13  32
  74  15 106  92  89  31  85  29   9   8  14   2 104 102  84  18  10  98
   6  93  96 103  12  11   7  95 100   4  97  16  99   3 101 107 112 109
 108 111 110]

In [44]:
df['latitude'].dtypes

dtype('float64')

In [45]:
print(df['latitude'].isnull().sum())

0

In [46]:
print(df['latitude'].unique())

[-30.613  10.859   0.643 ...  15.217 -44.002  13.084]

In [47]:
df['longitude'].dtypes

dtype('float64')

In [48]:
print(df['longitude'].isnull().sum())

0

In [49]:
print(df['longitude'].unique())

[-122.557 -159.194 -160.978 ...  -25.68  -147.346  -27.856]

### Distribution of key fields:

- Gender / Category columns

— This dataset does not contain a Gender column.

✓    The main categorical (category-type) columns are:
##### 1. country
##### 2. disaster_type

### Distribution explanation:
- country shows how disaster events are distributed across different countries worldwide.

- disaster_type shows the frequency of different types of disasters such as floods, earthquakes, cyclones, etc.

#### So , In Dataset we have no typos, outliers, or inconsistent present

## Phase-1 Conclusion
- The dataset was successfully cleaned and validated with no critical missing or
inconsistent values.
- The data is now ready for detailed exploratory and visual
analysis in Phase-2.